#!/usr/bin/env python3
import boto3
import argh
import cli_aws

def main(name):
    if name.startswith('vpc-'):
        return name
    else:
        ids = []
        for vpc in boto3.resource('ec2').vpcs.filter():
            if vpc.tags:
                for tag in vpc.tags:
                    if tag['Key'] == 'Name' and tag['Value'] == name:
                        ids.append(vpc.id)
        assert len(ids) == 1, f'didnt find exactly 1 vpc: {ids}'
        print(ids[0])

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
