#!/usr/bin/env python3
import shell
import boto3
import argh
import cli_aws
import sys

def main():
    for vpc in boto3.resource('ec2').vpcs.filter():
        name = '-'
        if vpc.tags:
            for tag in vpc.tags:
                if tag['Key'] == 'Name':
                    name = tag['Value']
        print(vpc.id, name)

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
