#!/usr/bin/env python3
import boto3
import argh
import cli_aws

def main(vpc_id, yes=False):
    if not vpc_id.startswith('vpc-'):
        vpcs = list(boto3.resource('ec2').vpcs.filter(Filters=[{'Name': 'tag:Name', 'Values': [vpc_id]}]))
        assert len(vpcs) == 1, vpcs
        vpc_id = vpcs[0].id
    vpc = boto3.resource('ec2').Vpc(vpc_id)
    for subnet in vpc.subnets.all():
        print(subnet.id)

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
