#!/usr/bin/env python3
import sys
import argh
import cli_aws

@argh.arg('--policy', action='append')
@argh.arg('--allow', action='append', help='"s3.Get $SOME_RESOURCE", or "s3:* *"')
def main(name, policy=None, allow=None):
    role_name = f'{name}-instance-profile-role'
    cli_aws.ensure_role(role_name, 'ec2')
    cli_aws.ensure_policies(role_name, policy or [])
    cli_aws.ensure_allows(role_name, allow or [])
    cli_aws.remove_extra_allows(role_name, allow or [])
    cli_aws.remove_extra_policies(role_name, policy or [])
    arn_profile = cli_aws.ensure_instance_profile(name, role_name)
    print('', file=sys.stderr)
    print(arn_profile)

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
