#!/bin/bash

echo idempotently create some common roles that are need to use EC2

aws iam create-role \
    --role-name aws-ec2-spot-fleet-tagging-role \
    --assume-role-policy-document '{"Version":"2012-10-17","Statement":[{"Sid":"","Effect":"Allow","Principal":{"Service":"spotfleet.amazonaws.com"},"Action":"sts:AssumeRole"}]}'

aws iam attach-role-policy \
    --role-name aws-ec2-spot-fleet-tagging-role \
    --policy-arn arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole

aws iam create-service-linked-role --aws-service-name spot.amazonaws.com

aws iam create-service-linked-role --aws-service-name spotfleet.amazonaws.com
