#!/usr/bin/env python3.6
import argh
import cli_aws

@argh.arg('--policy', action='append')
@argh.arg('--allow', action='append')
def main(name, principal, policy=None, allow=None):
    arn_role = cli_aws.ensure_role(name, principal)
    cli_aws.ensure_policies(name, policy or [])
    cli_aws.ensure_allows(name, allow or [])
    cli_aws.remove_extra_allows(name, allow or [])
    cli_aws.remove_extra_policies(name, policy or [])
    print(arn_role)

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
