#!/usr/bin/env python3
import shell
import boto3
import argh
import logging
import cli_aws

def main(ls_tags, set_tags, yes=False):
    instances = cli_aws.ls(ls_tags.split(','), None)
    assert instances, 'didnt find any instances for those tags'
    logging.info('going to tag the following instances:')
    for i in instances:
        logging.info(' ' + cli_aws.format(i))
    logging.info('with:')
    for t in set_tags.split(','):
        logging.info(' ' + t)
    if not yes:
        logging.info('\nwould you like to proceed? y/n\n')
        assert shell.getch() == 'y', 'abort'
    cli_aws.retry(boto3.client('ec2').create_tags)(
        Resources=[i.instance_id for i in instances],
        Tags=[{'Key': k, 'Value': v} for t in set_tags.split(',') for k, v in [t.split('=')]]
    )

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
