#!/usr/bin/env python3
import argh
import sys
import cli_aws

def main(*selectors, state='running'):
    instances = cli_aws.ls(selectors, state)
    if not instances:
        sys.exit(1)
    else:
        for instance in sorted(instances, key=lambda x: x.instance_id):
            print(instance.instance_id)

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
