#!/usr/bin/env python3.6
import boto3
import argh
import util.strings
import cli_aws

def main():
    text = '\n'.join('{KeyName} {KeyFingerprint}'.format(**key) for key in boto3.client('ec2').describe_key_pairs()['KeyPairs'])
    print(util.strings.align(text))

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
