#!/usr/bin/env python3
import boto3
import argh
import cli_aws
import shell

def main(vpc_name, sg_name):
    vpc_id = shell.run('aws-vpc-id', vpc_name, stream=False)
    sg_id = shell.run('aws-ec2-sg-id', sg_name, stream=False)
    [sg] = list(boto3.resource('ec2').security_groups.filter(GroupIds=[sg_id], Filters=[{'Name': 'vpc-id', 'Values': [vpc_id]}]))
    sg.delete()

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
