#!/usr/bin/env python3
import argh
import boto3
import cli_aws

def main(*ids):
    resp = boto3.client('ec2').describe_spot_fleet_requests()
    for fleet in sorted(resp['SpotFleetRequestConfigs'], key=lambda x: x['CreateTime'], reverse=True):
        yield ' '.join(map(str, [
            fleet['CreateTime'].strftime('%Y-%m-%dT%H:%M:%S'),
            fleet['SpotFleetRequestId'],
            fleet['SpotFleetRequestState'],
            fleet['SpotFleetRequestConfig']['TargetCapacity'],
        ]))

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
