#!/usr/bin/env python3
import argh
import sys
import cli_aws

def main(*selectors, state=None, all_tags=False):
    instances = cli_aws.ls(selectors, state)
    if not instances:
        sys.exit(1)
    else:
        for instance in instances:
            print(cli_aws.format(instance, all_tags))

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
