#!/usr/bin/env python3
import argh
import sys
import cli_aws

def main(*selectors, state='running'):
    instances = cli_aws.ls(selectors, state)
    if not instances:
        sys.exit(1)
    else:
        for instance in instances:
            print(cli_aws.green(cli_aws.tag_name(instance)),
                  instance.instance_id,
                  cli_aws.tag_name(instance.subnet),
                  instance.subnet.id,
                  instance.subnet.availability_zone)

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
