#!/usr/bin/env python3
import random
import logging
import shell
import argh
import cli_aws

def main(type, days=7):
    zones = {}
    for line in shell.run('aws-ec2-max-spot-price', type, '--days', days).splitlines():
        zone, price = line.split()
        zones[zone] = float(price)
    min_price = min(zones.values())
    cheap_zones = [zone for zone, price in zones.items() if price == min_price]
    logging.info('cheapest price %s', price)
    logging.info('available zones: %s', ','.join(cheap_zones))
    random.shuffle(cheap_zones)
    print(cheap_zones[0])

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
