#!/usr/bin/env python3
import itertools
import argh
import sys
import cli_aws
import shell
import util.colors
import pool.thread

def main(src, dst, *selectors, user='', yes=False, internal=False):
    assert selectors, 'you must specify some selectors'
    instances = cli_aws.ls(selectors, 'running')
    assert instances, 'didnt find any instances'
    if not instances:
        sys.exit(1)
    else:
        for instance in instances:
            print(cli_aws.format(instance), file=sys.stderr)
        if not yes:
            print('\nwould you like to proceed? y/n\n', file=sys.stderr)
            assert shell.getch() == 'y', 'abort'
        def run(instance, color):
            if color:
                color = getattr(util.colors, color)
            else:
                color = lambda x: x
            name = cli_aws.tag_name(instance) + ' ' + instance.id + ': '
            def fn():
                host = (user or cli_aws.ssh_user(instance)) + '@' + (instance.private_ip_address if internal else instance.public_dns_name)
                _src = host + src if src.startswith(':') else src
                _dst = host + dst if dst.startswith(':') else dst
                try:
                    shell.run('scp',
                              cli_aws.ssh_args,
                              _src,
                              _dst,
                              callback=lambda _, x: print(color(name + x), file=sys.stderr, flush=True))
                except:
                    failures.append(util.colors.red('failure: ') + cli_aws.tag_name(instance) + ' ' + instance.id)
                else:
                    successes.append(util.colors.green('success: ') + cli_aws.tag_name(instance) + ' ' + instance.id)
            return fn
        failures = []
        successes = []
        pool.thread.wait(*map(run, instances, itertools.cycle(util.colors._colors) if len(instances) > 1 else [False]))
        print('\nresults:', file=sys.stderr)
        for msg in successes + failures:
            print(' ' + msg)
        if failures:
            sys.exit(1)

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
