#!/usr/bin/env python3.6
import argh
import sys
import cli_aws

def main(*selectors):
    instances = cli_aws.ls(selectors, 'running')
    if not instances:
        sys.exit(1)
    else:
        for instance in sorted(instances, key=lambda x: x.instance_id):
            print(instance.public_dns_name)

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
