#!/usr/bin/env python3
import logging
import argh
import cli_aws
import boto3

def main(id_only=False):
    amis = boto3.resource('ec2').images.filter(
        Owners=['self'],
        Filters=[{'Name': 'state',
                  'Values': ['available']}]
    )
    amis = sorted(amis, key=lambda x: x.creation_date, reverse=True)
    if id_only:
        return [ami.image_id for ami in amis]
    else:
        def f(ami):
            try:
                name, date = ami.name.split('__')
            except ValueError:
                return
            else:
                description = ami.description or '-' if ami.description != name else '-'
                tags = ','.join('%(Key)s=%(Value)s' % tag for tag in ami.tags) if ami.tags else '-'
                return ' '.join([name, ami.image_id, date, description, tags])
        logging.info('id date description tags...')
        xs = [f(ami) for ami in amis]
        return [x for x in xs if x]

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
