#!/usr/bin/env python3
import logging
import shell
import argh
import cli_aws

def main(type, days=7):
    zone, price = shell.run('aws-ec2-max-spot-price', type, '--days', days).splitlines()[0].split()
    logging.info('cheapest price %s', price)
    print(zone)

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
