#!/usr/bin/env python3.6
import argh
import sys
import aws_util

def main(*selectors):
    instances = aws_util.ls(selectors, 'running')
    if not instances:
        sys.exit(1)
    else:
        for instance in sorted(instances, key=lambda x: x.instance_id):
            print(instance.private_dns_name)

if __name__ == '__main__':
    with aws_util.setup():
        argh.dispatch_command(main)
