#!/usr/bin/env python3.6
import datetime
import boto3
import os
import argh
import aws_util

def main(path, limit=100):
    group_name = f'/aws/lambda/{aws_util.lambda_name(path)}'
    stream_name = boto3.client('logs').describe_log_streams(logGroupName=group_name, orderBy='LastEventTime')['logStreams'][-1]['logStreamName']
    logs = boto3.client('logs').get_log_events(logGroupName=group_name, logStreamName=stream_name, limit=limit)['events']
    print('log group:', group_name)
    print('log stream:', stream_name)
    for log in logs:
        print(datetime.datetime.fromtimestamp(log['timestamp'] / 1000),
              log['message'].replace('\t', ' ').strip())

if __name__ == '__main__':
    with aws_util.setup():
        argh.dispatch_command(main)
