#!/usr/bin/env python3.6
import argh
import aws_util
import boto3

def main(path):
    with open(path) as f:
        topics = aws_util.parse_metadata('trigger-sns:', f.read().splitlines())
    for page in boto3.client('sns').get_paginator('list_topics').paginate():
        for topic in page['Topics']:
            arn = topic['TopicArn']
            if arn.split(':')[-1] in topics:
                print(arn)

if __name__ == '__main__':
    with aws_util.setup():
        argh.dispatch_command(main)
