#!/usr/bin/env python3.6
import boto3
import logging
import argh
import aws_util
import shell
from util.retry import retry

def main(*selectors, yes=False):
    assert selectors, 'you cannot rm all things, specify some selectors'
    assert selectors != ('*',), 'you cannot rm all things, specify some selectors'
    pendings = aws_util.ls(selectors, 'pending')
    if pendings:
        logging.info('wait for pending instances before rm:')
        for pending in pendings:
            logging.info(' %s', aws_util.format(pending))
        shell.check_call('aws-ec2-wait-for-state -e running', *[i.instance_id for i in pendings])
    instances = [i for i in aws_util.ls(selectors, None) if i.state['Name'] in ['running', 'stopped']]
    assert instances, 'didnt find any instances for those selectors'
    logging.info('going to terminate the following instances:')
    for i in instances:
        logging.info(' ' + aws_util.format(i))
    if not yes:
        logging.info('\nwould you like to proceed? y/n\n')
        assert shell.getch() == 'y', 'abort'
    retry(boto3.client('ec2').terminate_instances)(InstanceIds=[i.instance_id for i in instances])

if __name__ == '__main__':
    with aws_util.setup():
        argh.dispatch_command(main)
