#!/usr/bin/env python3.6
import os
import argh
import aws_util
import shell

def main(path, payload=None):
    if payload:
        payload = f'--payload file://{payload}'
    else:
        payload = ''
    print(shell.run(f'aws lambda invoke {payload} --function-name {aws_util.lambda_name(path)} >(cat -)'))

if __name__ == '__main__':
    with aws_util.setup():
        argh.dispatch_command(main)
