#!/usr/bin/env python3.6
import argh
import sys
import aws_util as util

def main(*selectors, state='running'):
    instances = util.ls(selectors, state)
    if not instances:
        sys.exit(1)
    else:
        for instance in sorted(instances, key=lambda x: x.instance_id):
            print(instance.instance_id)

if __name__ == '__main__':
    with util.setup():
        argh.dispatch_command(main)
