#!/usr/bin/env python3.6
import argh
import sys
import aws_util as util

def main(*selectors, state='running'):
    instances = util.ls(selectors, state)
    if not instances:
        sys.exit(1)
    else:
        for instance in instances:
            print(util.green(util.name(instance)),
                  instance.instance_id,
                  util.name(instance.subnet),
                  instance.subnet.id,
                  instance.subnet.availability_zone)

if __name__ == '__main__':
    with util.setup():
        argh.dispatch_command(main)
