#!/usr/bin/env python3.6
import argh
import sys
import aws_util

def main(*selectors, state=None, all_tags=False):
    instances = aws_util.ls(selectors, state)
    if not instances:
        sys.exit(1)
    else:
        for instance in instances:
            print(aws_util.format(instance, all_tags))

if __name__ == '__main__':
    with aws_util.setup():
        argh.dispatch_command(main)
