#!/usr/bin/env python3.6
import util.exceptions
import json
import argh
import cli_aws
import boto3

def main(path):
    name = cli_aws.lambda_name(path)
    print('name:', name)

    with util.exceptions.ignore(boto3.client('iam').exceptions.NoSuchEntityException):
        policies = boto3.client('iam').list_attached_role_policies(RoleName=name)['AttachedPolicies']
        if policies:
            print()
            print('attached policies:')
            for policy in policies:
                print('', policy['PolicyName'])

    with util.exceptions.ignore(boto3.client('iam').exceptions.NoSuchEntityException):
        policies = boto3.client('iam').list_role_policies(RoleName=name)['PolicyNames']
        if policies:
            print()
            print('attached policies:')
            for policy in policies:
                print('', policy)
                print(util.strings.indent(json.dumps(boto3.client('iam').get_role_policy(RoleName=name, PolicyName=policy)['PolicyDocument'], indent=2), 2))

    with util.exceptions.ignore(boto3.client('iam').exceptions.NoSuchEntityException):
        policy = boto3.client('iam').get_role(RoleName=name)['Role']["AssumeRolePolicyDocument"]
        print()
        print('role:')
        print(util.strings.indent(json.dumps(policy, indent=2), 2))

    with util.exceptions.ignore(boto3.client('lambda').exceptions.ResourceNotFoundException):
        resp = json.loads(boto3.client('lambda').get_policy(FunctionName=name)['Policy'])
        if resp:
            print()
            print('function policy:')
            print(util.strings.indent(json.dumps(resp, indent=2), 2))

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
