#!/usr/bin/env python3.6
import boto3
import argh
import cli_aws

def main(path, limit=100):
    print(boto3.client('lambda').get_function(FunctionName=cli_aws.lambda_name(path))['Configuration']['FunctionArn'])

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
