#!/usr/bin/env python3
import util.colors
import argh
import cli_aws
import boto3

def main():
    fns = []
    for page in boto3.client('lambda').get_paginator('list_functions').paginate():
        for fn in page['Functions']:
            fn['FunctionName'] = util.colors.green(fn['FunctionName'])
            fn['LastModified'] = ':'.join(fn['LastModified'].split(':')[:2]) + 'Z'
            fns.append(fn)
    for fn in sorted(fns, key=lambda x: x['LastModified'], reverse=True):
        print('{FunctionName} {Runtime} {Timeout}s {MemorySize}mb {LastModified}'.format(**fn))

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
