#!/usr/bin/env python3.6
import argh
import aws_util
import boto3

def main(path):
    name = aws_util.lambda_name(path)
    with open(path) as f:
        triggers = aws_util.parse_metadata('trigger:', f.read().splitlines())
    if 'sns' in triggers:
        for page in boto3.client('sns').get_paginator('list_topics').paginate():
            for topic in page['Topics']:
                arn = topic['TopicArn']
                if arn.split(':')[-1] == name:
                    print(arn)

if __name__ == '__main__':
    with aws_util.setup():
        argh.dispatch_command(main)
