#!/usr/bin/env python3.6
import sys
import time
import datetime
import boto3
import argh
import aws_util

def main(path,
         follow: 'like tail -f' = False,
         number: 'when following, after printing this many lines, exit' = 0):
    group_name = f'/aws/lambda/{aws_util.lambda_name(path)}'
    print('log group:', group_name)
    if follow:
        token = ''
        last_stream = None
        started = False
        printed = 0
        while True:
            try:
                stream_name = boto3.client('logs').describe_log_streams(logGroupName=group_name, orderBy='LastEventTime')['logStreams'][-1]['logStreamName']
                if last_stream != stream_name:
                    print('log stream:', stream_name)
                    last_stream = stream_name
            except boto3.client('logs').exceptions.ResourceNotFoundException:
                pass
            else:
                kw = {}
                if token:
                    kw['nextToken'] = token
                if not started:
                    kw['limit'] = 1
                resp = boto3.client('logs').get_log_events(logGroupName=group_name, logStreamName=stream_name, **kw)
                token = resp['nextForwardToken']
                logs = resp['events']
                for log in logs:
                    if not started:
                        started = True
                    else:
                        printed += 1
                        print(datetime.datetime.fromtimestamp(log['timestamp'] / 1000),
                              log['message'].replace('\t', ' ').strip())
                        if number and printed >= number:
                            sys.exit(0)
            time.sleep(1)
    else:
        stream_name = boto3.client('logs').describe_log_streams(logGroupName=group_name, orderBy='LastEventTime')['logStreams'][-1]['logStreamName']
        print('log stream:', stream_name)
        logs = boto3.client('logs').get_log_events(logGroupName=group_name, logStreamName=stream_name)['events']
        for log in logs:
            print(datetime.datetime.fromtimestamp(log['timestamp'] / 1000),
                  log['message'].replace('\t', ' ').strip())


if __name__ == '__main__':
    with aws_util.setup():
        argh.dispatch_command(main)
