#!/usr/bin/env python3.6
import boto3
import argh
import aws_util

def main(path, limit=100):
    print(boto3.client('lambda').get_function(FunctionName=aws_util.lambda_name(path))['Configuration']['FunctionArn'])

if __name__ == '__main__':
    with aws_util.setup():
        argh.dispatch_command(main)
