#!/usr/bin/env python3.6
import argh
import cli_aws
import boto3

def main(path):
    name = cli_aws.lambda_name(path)
    with open(path) as f:
        triggers = cli_aws.parse_metadata('trigger:', f.read().splitlines(), silent=True)
    if 'sns' in triggers:
        for page in boto3.client('sns').get_paginator('list_topics').paginate():
            for topic in page['Topics']:
                arn = topic['TopicArn']
                if arn.split(':')[-1] == name:
                    print(arn)

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
