#!/usr/bin/env python3.6
import sys
import tempfile
import os
import argh
import aws_util
import shell

def main(path, payload=None):
    if payload:
        payload = f'--payload file://{payload}'
    else:
        payload = ''
    _, temp = tempfile.mkstemp()
    print(shell.run(f'aws lambda invoke {payload} --function-name {aws_util.lambda_name(path)} {temp}'), file=sys.stderr)
    with open(temp) as f:
        print(f.read())
    os.remove(temp)

if __name__ == '__main__':
    with aws_util.setup():
        argh.dispatch_command(main)
