#!/usr/bin/env python3
import util.strings
import boto3
import sys
import argh
import cli_aws

@argh.arg('-p', '--payload')
def main(path, payload=None, event=False):
    resp = boto3.client('lambda').invoke(
        FunctionName=cli_aws.lambda_name(path),
        InvocationType='Event' if event else 'RequestResponse',
        LogType=None if event else 'Tail',
        Payload=open(payload, 'rb') if payload else '',
    )
    print(util.strings.b64_decode(resp['LogResult']), file=sys.stderr)
    print(resp['Payload'].read().decode('utf-8'))

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
