#!/usr/bin/env python3.6
import argh
import aws_util

def main(path, limit=100):
    return aws_util.lambda_name(path)

if __name__ == '__main__':
    with aws_util.setup():
        argh.dispatch_command(main)
