#!/usr/bin/env python3.6
import argh
import cli_aws

def main(path, limit=100):
    return cli_aws.lambda_name(path)

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
