#!/usr/bin/env python3
import argh
import cli_aws
import boto3

def main(path):
    name = cli_aws.lambda_name(path)
    for k, v in boto3.client('lambda').get_function(FunctionName=name)['Configuration']['Environment']['Variables'].items():
        print(f'{k}={v}')

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
