#!/usr/bin/env python3
import util.dicts
import util.iter
import json
import argh
import cli_aws
import boto3
from util.retry import retry

def f(v):
    if isinstance(v, dict) and len(v) == 1 and list(v)[0] in ['S', 'N', 'B', 'L', 'M', 'BOOL']:
        v = list(v.values())[0]
    return v

def main(table, max=1000, page_size=100, verbose=False):
    resp = retry(boto3.client('dynamodb').get_paginator('scan').paginate)(
        TableName=table,
        PaginationConfig={
            'MaxItems': max,
            'PageSize': page_size,
        }
    )
    for items in resp:
        for item in items['Items']:
            if verbose:
                print(json.dumps(item))
            else:
                print(json.dumps(util.iter.walk(f, item)))

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
