#!/usr/bin/env python3.6
import json
import argh
import cli_aws
import boto3
from util.retry import retry

def main(table, *keys):
    """
    delete item
    describe keys like: $name:$value:s|n|b
    example: user_name:john:s
    """
    return json.dumps(retry(boto3.client('dynamodb').delete_item)(
        TableName=table,
        Key={name: {type.upper(): value}
             for key in keys
             for name, value, type in [key.split(':')]}
    ))

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
