#!/usr/bin/env python3.6
import json
import argh
import cli_aws
import boto3
from util.retry import retry

def main(table, max=1000, page_size=100, verbose=False):
    resp = retry(boto3.client('dynamodb').get_paginator('scan').paginate)(
        TableName=table,
        PaginationConfig={
            'MaxItems': max,
            'PageSize': page_size,
        }
    )
    for items in resp:
        for item in items['Items']:
            if verbose:
                print(json.dumps(item))
            else:
                print(json.dumps({k: v.popitem()[1] for k, v in item.items()}))

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
