#!/usr/bin/env python3
import argh
import cli_aws
import boto3
from util.retry import retry

def main():
    for page in retry(boto3.client('dynamodb').get_paginator('list_tables').paginate)():
        for name in page['TableNames']:
            print(name)

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
