#!/usr/bin/env python3.6
import argh
import cli_aws
import boto3
from util.retry import retry

def main(table, *vals):
    """
    put item
    describe vals like: $name:$value:s|n|b
    example: user_name:john:s
    """
    retry(boto3.client('dynamodb').put_item)(
        TableName=table,
        Item={name: {type.upper(): value}
              for val in vals
              for name, value, type in [val.split(':')]}
    )

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
