#!/usr/bin/env python3
import argh
import shell
import cli_aws

def main():
    with shell.cd('~/.aws_creds'):
        creds = []
        for cred_path in shell.files():
            with open(cred_path) as f:
                text = f.read()
            if 'AWS_ACCESS_KEY_ID=' in text and 'AWS_SECRET_ACCESS_KEY=' in text and 'AWS_DEFAULT_REGION=' in text and cred_path != '_temp_creds.sh':
                creds.append(cred_path)
        print('~/.aws_creds/')
        for cred in creds:
            print('', cred)

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
