#!/usr/bin/env python3
import os
import sys
import argh
import shell
import cli_aws

def main(name):
    with shell.cd('~/.aws_creds'):
        creds = []
        for cred_path in shell.files():
            with open(cred_path) as f:
                text = f.read()
            if 'AWS_ACCESS_KEY_ID' in text and 'AWS_SECRET_ACCESS_KEY' in text and 'AWS_DEFAULT_REGION' in text:
                creds.append(cred_path)
            if name + '.sh' == cred_path:
                print(f'{cred_path} > ~/.aws_creds/_temp_creds.sh', file=sys.stderr)
                shell.run(f'echo export AWS_CREDS_NAME={cred_path.split(".")[0]} > _temp_creds.sh')
                shell.run(f'cat {cred_path} | grep export >> _temp_creds.sh')
                return os.path.abspath(cred_path)
        print('fatal: no match, try:\n')
        for cred in creds:
            if '_temp' not in cred:
                print('            ', cred.split('.')[0])
        sys.exit(1)

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
