#!/usr/bin/env python3
import boto3
import argh
import cli_aws
from cli_aws import retry

def main():
    zones = (zone
             for page in retry(boto3.client('route53').get_paginator('list_hosted_zones').paginate)()
             for zone in page['HostedZones'])
    for zone in zones:
        print(zone['Name'])
        records = (record
                   for page in retry(boto3.client('route53').get_paginator('list_resource_record_sets').paginate)(HostedZoneId=zone['Id'])
                   for record in page['ResourceRecordSets'])
        for record in records:
            if 'AliasTarget' in record:
                record['Value'] = record['AliasTarget']['DNSName']
                print('- {Name} Alias => {Value}'.format(**record))
            else:
                record['Value'] = ' '.join(r['Value'] for r in record['ResourceRecords'])
                print('- {Name} {Type} {TTL} => {Value}'.format(**record))
        print()

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
