#!/usr/bin/env python3.6
import boto3
import argh
import cli_aws

def main():
    boto3.setup_default_session()
    session = boto3.DEFAULT_SESSION
    for profile in session.available_profiles:
        print(profile)

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
