#!/usr/bin/env python3
import argh
import boto3
import cli_aws

def main():
    return boto3.client('sts').get_caller_identity()['Account']

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
