#!/usr/bin/env python3
import argh
import cli_aws

def main():
    for region in cli_aws.regions():
        print(region)

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
