#!/usr/bin/env python3
import argh
import cli_aws

def main():
    for zone in cli_aws.zones():
        print(zone)

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
