#!/usr/bin/env python3
# type: ignore
import logging
import boto3
import argh
import cli_aws

def main(state=None):
    kw = {}
    if state:
        assert state.upper() in ['STARTING', 'BOOTSTRAPPING', 'RUNNING', 'WAITING', 'TERMINATING', 'TERMINATED', 'TERMINATED_WITH_ERRORS']
        kw['ClusterStates'] = [state.upper()]
    logging.info('name id instance-hours state creation-date')
    for resp in boto3.client('emr').get_paginator('list_clusters').paginate(**kw):
        for cluster in resp['Clusters']:
            yield ' '.join(map(str, [
                cluster['Name'],
                cluster['Id'],
                cluster['NormalizedInstanceHours'],
                cluster['Status']['State'],
                cluster['Status']['Timeline']['CreationDateTime'],
            ]))

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
