#!/usr/bin/env python3
# type: ignore
import argh
import cli_aws
import shell

def main(cluster_id, cmd=''):
    ip = shell.run("aws-emr-ip", cluster_id)
    if cmd:
        with shell.tempdir():
            with open('script.sh', 'w') as f:
                f.write(cmd)
            shell.check_call(f'aws-ec2-ssh {ip} -yc script.sh')
    else:
        shell.check_call(f'aws-ec2-ssh {ip}')

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
