#!/usr/bin/env python3
# type: ignore
import argh
import cli_aws
import shell

def main(cluster_id):
    return shell.run(f"aws-ec2-ip aws:elasticmapreduce:instance-group-role=MASTER aws:elasticmapreduce:job-flow-id={cluster_id}")

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
