#!/usr/bin/env python3
# type: ignore
import boto3
import argh
import json
import cli_aws

def main(*cluster_ids):
    resp = boto3.client('emr').terminate_job_flows(JobFlowIds=cluster_ids)
    print(json.dumps(resp, indent=4))

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
