#!/usr/bin/env python3
# type: ignore
import argh
import cli_aws
import shell

def main(src, dst, cluster_id):
    ip = shell.run("aws-emr-ip", cluster_id)
    shell.run(f'aws-ec2-scp -y "{src}" "{dst}" {ip}', stream=True)

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
