#!/usr/bin/env python3
# type: ignore
import boto3
import argh
import cli_aws

def main(cluster_id, state='running'):
    boto3.client('emr').get_waiter('cluster_%s' % state).wait(ClusterId=cluster_id)

if __name__ == '__main__':
    with cli_aws.setup():
        argh.dispatch_command(main)
